"use client";

import { useState, type FormEvent } from "react";
import type { DefinitionRecord } from "./work-types";
import styles from "./DefineWorkspace.module.css";

type Control = NonNullable<DefinitionRecord["scopeControl"]>;
const blank: Control = { requirements: [], interfaces: [], assumptions: [] };
const value = (data: FormData, key: string) => String(data.get(key) ?? "").trim();

export function DefineScopeControls({ control, locked, onChange, area }: { control?: Control; locked: boolean; area: "scope" | "delivery"; onChange: (next: Control) => void }) {
  const current = { ...blank, ...control };
  const [drawer, setDrawer] = useState<"requirement" | "interface" | "assumption" | "agreement" | "rom" | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [error, setError] = useState("");
  const requirement = current.requirements.find((item) => item.id === editingId);
  const boundary = current.interfaces.find((item) => item.id === editingId);
  const assumption = current.assumptions.find((item) => item.id === editingId);
  const open = (kind: NonNullable<typeof drawer>, id: string | null = null) => { setError(""); setEditingId(id); setDrawer(kind); };
  function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!drawer || locked) return;
    const data = new FormData(event.currentTarget);
    if (drawer === "rom" && Number(value(data, "low")) > Number(value(data, "high"))) { setError("The high ROM amount must be at least the low amount."); return; }
    if (drawer === "requirement") { const item = { id: editingId ?? crypto.randomUUID(), need: value(data, "need"), source: value(data, "source"), owner: value(data, "owner"), state: value(data, "state") as "Open" | "Confirmed" }; onChange({ ...current, requirements: editingId ? current.requirements.map((row) => row.id === editingId ? item : row) : [...current.requirements, item] }); }
    if (drawer === "interface") { const item = { id: editingId ?? crypto.randomUUID(), kind: value(data, "kind") as Control["interfaces"][number]["kind"], boundary: value(data, "boundary"), owner: value(data, "owner"), counterparty: value(data, "counterparty"), agreement: value(data, "agreement") }; onChange({ ...current, interfaces: editingId ? current.interfaces.map((row) => row.id === editingId ? item : row) : [...current.interfaces, item] }); }
    if (drawer === "assumption") { const item = { id: editingId ?? crypto.randomUUID(), statement: value(data, "statement"), owner: value(data, "owner"), source: value(data, "source"), state: value(data, "state") as "Open" | "Accepted" | "Resolved" }; onChange({ ...current, assumptions: editingId ? current.assumptions.map((row) => row.id === editingId ? item : row) : [...current.assumptions, item] }); }
    if (drawer === "agreement") onChange({ ...current, customerAgreement: { representative: value(data, "representative"), agreedAt: value(data, "agreedAt"), basis: value(data, "basis") } });
    if (drawer === "rom") onChange({ ...current, rom: { low: value(data, "low"), high: value(data, "high"), currency: value(data, "currency"), assumptions: value(data, "assumptions") } });
    setDrawer(null);
    setEditingId(null);
  }
  return <div className={styles.scopeControls}>
    {area === "scope" ? <>
    <section className={styles.register}><header><div><strong>Customer requirements</strong><p>Capture the need, its source, accountable owner, and confirmation state before defining a deliverable.</p></div><span>{current.requirements.length} recorded</span></header>
      {current.requirements.map((item) => <article key={item.id} className={styles.investigationRow}><strong>{item.state} · {item.need}</strong><small>Source: {item.source} · Owner: {item.owner}</small>{!locked ? <div className={styles.inlineActions}><button type="button" className="d5o-outline" onClick={() => open("requirement", item.id)}>Edit</button><button type="button" className="d5o-outline" onClick={() => onChange({ ...current, requirements: current.requirements.map((row) => row.id === item.id ? { ...row, state: row.state === "Open" ? "Confirmed" : "Open" } : row) })}>{item.state === "Open" ? "Confirm source" : "Reopen"}</button><button type="button" className="d5o-outline" onClick={() => onChange({ ...current, requirements: current.requirements.filter((row) => row.id !== item.id) })}>Remove</button></div> : null}</article>)}
      {!locked ? <button type="button" className={styles.addRow} onClick={() => open("requirement")}>+ Add requirement</button> : null}</section>
    <section className={styles.register}><header><div><strong>Customer scope agreement</strong><p>Record the person, date, and traceable meeting or document basis. This is not an offer or award.</p></div></header><p className={styles.controlText}>{current.customerAgreement ? `${current.customerAgreement.representative} · ${current.customerAgreement.agreedAt} · ${current.customerAgreement.basis}` : "No customer scope agreement recorded."}</p>{!locked ? <button type="button" className={styles.addRow} onClick={() => open("agreement")}>Record agreement</button> : null}</section>
    </> : null}
    {area === "delivery" ? <>
    <section className={styles.register}><header><div><strong>Owned interfaces</strong><p>Identify where customer, partner, third party, and delivery responsibilities meet.</p></div><span>{current.interfaces.length} recorded</span></header>{current.interfaces.map((item) => <article key={item.id} className={styles.investigationRow}><strong>{item.kind} · {item.boundary}</strong><small>{item.owner} ↔ {item.counterparty} · {item.agreement}</small>{!locked ? <div className={styles.inlineActions}><button type="button" className="d5o-outline" onClick={() => open("interface", item.id)}>Edit</button><button type="button" className="d5o-outline" onClick={() => onChange({ ...current, interfaces: current.interfaces.filter((row) => row.id !== item.id) })}>Remove</button></div> : null}</article>)}{!locked ? <button type="button" className={styles.addRow} onClick={() => open("interface")}>+ Add interface</button> : null}</section>
    <section className={styles.register}><header><div><strong>Assumptions and constraints</strong><p>Open assumptions stay visible and block a positive scope decision until dispositioned.</p></div><span>{current.assumptions.filter((item) => item.state === "Open").length} open</span></header>{current.assumptions.map((item) => <article key={item.id} className={styles.investigationRow}><strong>{item.state} · {item.statement}</strong><small>{item.owner} · Source: {item.source}</small>{!locked ? <div className={styles.inlineActions}><button type="button" className="d5o-outline" onClick={() => open("assumption", item.id)}>Edit</button><button type="button" className="d5o-outline" onClick={() => onChange({ ...current, assumptions: current.assumptions.map((row) => row.id === item.id ? { ...row, state: row.state === "Open" ? "Accepted" : "Open" } : row) })}>{item.state === "Open" ? "Accept basis" : "Reopen"}</button><button type="button" className="d5o-outline" onClick={() => onChange({ ...current, assumptions: current.assumptions.filter((row) => row.id !== item.id) })}>Remove</button></div> : null}</article>)}{!locked ? <button type="button" className={styles.addRow} onClick={() => open("assumption")}>+ Add assumption</button> : null}</section>
    <section className={styles.register}><header><div><strong>Preliminary budget alignment</strong><p>Optional ROM only. Detailed estimate, pricing approval, offer, and award belong to Develop.</p></div></header><p className={styles.controlText}>{current.rom?.low && current.rom.high ? `${current.rom.currency} ${current.rom.low}–${current.rom.high} · ${current.rom.assumptions}` : "No preliminary range recorded."}</p>{!locked ? <button type="button" className={styles.addRow} onClick={() => open("rom")}>Record ROM range</button> : null}</section>
    </> : null}
    {drawer ? <div className={styles.drawerBackdrop} onMouseDown={(event) => { if (event.target === event.currentTarget) setDrawer(null); }}><aside className={styles.drawer} role="dialog" aria-modal="true" aria-label={`Define ${drawer}`}><header><div><p className={styles.kicker}>DEFINE · CONTROLLED BASIS</p><h3>{({ requirement: "Customer requirement", interface: "Responsibility interface", assumption: "Assumption or constraint", agreement: "Customer scope agreement", rom: "Preliminary budget range" })[drawer]}</h3></div><button type="button" className="d5o-outline" onClick={() => setDrawer(null)} aria-label="Close drawer">×</button></header><form className={styles.drawerForm} onSubmit={save}>
      {drawer === "requirement" ? <><label>Requirement<input name="need" defaultValue={requirement?.need} required /></label><label>Source reference<input name="source" defaultValue={requirement?.source} required placeholder="Customer meeting, survey, document or finding" /></label><label>Accountable owner<input name="owner" defaultValue={requirement?.owner} required /></label><label>State<select name="state" defaultValue={requirement?.state ?? "Open"}><option>Open</option><option>Confirmed</option></select></label></> : null}
      {drawer === "interface" ? <><label>Interface type<select name="kind" defaultValue={boundary?.kind ?? "Physical"}><option>Physical</option><option>Technical</option><option>Organizational</option><option>Commercial</option></select></label><label>Boundary or hand-off point<input name="boundary" defaultValue={boundary?.boundary} required /></label><label>Our owner<input name="owner" defaultValue={boundary?.owner} required /></label><label>Customer or third-party owner<input name="counterparty" defaultValue={boundary?.counterparty} required /></label><label>Agreed responsibility or source<textarea name="agreement" rows={3} defaultValue={boundary?.agreement} required /></label></> : null}
      {drawer === "assumption" ? <><label>Assumption or constraint<textarea name="statement" rows={3} defaultValue={assumption?.statement} required /></label><label>Owner<input name="owner" defaultValue={assumption?.owner} required /></label><label>Source or resolution basis<input name="source" defaultValue={assumption?.source} required /></label><label>Disposition<select name="state" defaultValue={assumption?.state ?? "Open"}><option>Open</option><option>Accepted</option><option>Resolved</option></select></label></> : null}
      {drawer === "agreement" ? <><label>Customer representative<input name="representative" defaultValue={current.customerAgreement?.representative} required /></label><label>Date agreed<input type="date" name="agreedAt" defaultValue={current.customerAgreement?.agreedAt} required /></label><label>Meeting or document reference<input name="basis" defaultValue={current.customerAgreement?.basis} required /></label><p className={styles.drawerHelp}>A typed reference records the claimed basis; it does not verify a customer signature or uploaded file.</p></> : null}
      {drawer === "rom" ? <><label>Low amount<input type="number" min="0" name="low" defaultValue={current.rom?.low} required /></label><label>High amount<input type="number" min="0" name="high" defaultValue={current.rom?.high} required /></label><label>Currency<input name="currency" defaultValue={current.rom?.currency ?? "USD"} required /></label><label>Range assumptions<textarea name="assumptions" rows={3} defaultValue={current.rom?.assumptions} required /></label></> : null}
      {error ? <p className={styles.baselineBlocker} role="alert">{error}</p> : null}<footer><button type="button" className="d5o-outline" onClick={() => setDrawer(null)}>Cancel</button><button type="submit" className="d5o-primary">Save to Define revision</button></footer></form></aside></div> : null}
  </div>;
}
