"use client";

import { useState } from "react";
import type { PublishedPhaseContract } from "./published-phase-configuration";
import type { PhaseKey } from "./phase-configuration";
import { designReviewDisciplines } from "./design-policy";
import { defaultDeployControlPolicy } from "./deploy-policy";
import { defaultOperateControlPolicy } from "./operate-policy";

const phaseKeys: PhaseKey[] = ["discover", "define", "develop", "design", "deploy", "operate"];

export function PhaseContractEditor({ value, onChange }: { value: PublishedPhaseContract; onChange: (next: PublishedPhaseContract) => void }) {
  const [selectedType, setSelectedType] = useState(value.workTypes[0]?.workTypeKey ?? "");
  const [selectedPhase, setSelectedPhase] = useState<PhaseKey>("discover");
  const [newField, setNewField] = useState<Record<string, string>>({});
  const workType = value.workTypes.find((item) => item.workTypeKey === selectedType) ?? value.workTypes[0];
  const phase = workType?.phases.find((item) => item.key === selectedPhase);
  const update = (change: (draft: PublishedPhaseContract) => void) => { const draft = structuredClone(value); change(draft); onChange(draft); };
  const componentAt = (draft: PublishedPhaseContract, key: string) => draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.phases.find((item) => item.key === selectedPhase)!.components.find((item) => item.key === key)!;
  if (!workType || !phase) return <p>Phase contract unavailable.</p>;
  return <section className="d5o-phase-editor" aria-label="D5O phase form contract">
    <div className="d5o-phase-editor-heading"><div><strong>Structured phase form contract</strong><span>Fields and required register columns are published with this version. Bound facts, decision guards and database authority cannot be changed here.</span></div></div>
    <div className="d5o-phase-editor-tabs" role="group" aria-label="Work Type">{value.workTypes.map((item) => <button type="button" key={item.workTypeKey} aria-pressed={workType.workTypeKey === item.workTypeKey} onClick={() => setSelectedType(item.workTypeKey)}>{item.workTypeLabel}</button>)}</div>
    <div className="d5o-phase-editor-tabs" role="group" aria-label="Phase">{phaseKeys.map((key) => <button type="button" key={key} aria-pressed={selectedPhase === key} onClick={() => setSelectedPhase(key)}>{key}</button>)}</div>
    {selectedPhase !== "discover" && selectedPhase !== "define" ? <p className="d5o-phase-editor-preview-note">Structured solution, verification and handoff entries use this published form version. Packages, crew, execution, evidence and lifecycle actions remain on their existing Work Record surfaces. Authoritative decisions stay with the server command contract.</p> : null}
    <label>Phase purpose<input value={phase.purpose} maxLength={240} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.phases.find((item) => item.key === selectedPhase)!.purpose = event.target.value; })} /></label>
    <div className="d5o-phase-editor-components">{phase.components.map((item) => <article key={item.key}>
      <small>{item.kind.replaceAll("_", " ")} · {item.key}</small>
      <label>Section label<input value={item.label} maxLength={120} onChange={(event) => update((draft) => { componentAt(draft, item.key).label = event.target.value; })} /></label>
      <label>Guidance<input value={item.help} maxLength={500} onChange={(event) => update((draft) => { componentAt(draft, item.key).help = event.target.value; })} /></label>
      {item.fields?.length ? <div className="d5o-phase-editor-fields"><strong>Structured fields</strong>{item.fields.map((field) => <div key={field.key} className="d5o-phase-editor-field"><label>{field.key}<input value={field.label} maxLength={120} onChange={(event) => update((draft) => { componentAt(draft, item.key).fields!.find((entry) => entry.key === field.key)!.label = event.target.value; })} /></label><label className="d5o-phase-editor-check"><input type="checkbox" checked={field.required} disabled={item.kind !== "item_register"} onChange={(event) => update((draft) => { const component = componentAt(draft, item.key); component.fields!.find((entry) => entry.key === field.key)!.required = event.target.checked; for (const rule of component.rules ?? []) if (rule.operator === "rows_complete") rule.fields = component.fields!.filter((entry) => entry.required).map((entry) => entry.key); })} /> Required for review</label></div>)}{item.kind === "item_register" ? <div className="d5o-phase-editor-add"><input aria-label={`New ${item.label} field`} value={newField[item.key] ?? ""} maxLength={80} placeholder="New field name" onChange={(event) => setNewField((current) => ({ ...current, [item.key]: event.target.value }))} /><button type="button" disabled={!newField[item.key]?.trim()} onClick={() => { const label = newField[item.key]?.trim() ?? ""; const key = label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, ""); if (key.length < 2 || item.fields?.some((field) => field.key === key)) return; update((draft) => { const component = componentAt(draft, item.key); component.fields!.push({ key, label, kind: "text", required: true }); for (const rule of component.rules ?? []) if (rule.operator === "rows_complete") rule.fields = component.fields!.filter((entry) => entry.required).map((entry) => entry.key); }); setNewField((current) => ({ ...current, [item.key]: "" })); }}>Add field</button></div> : null}</div> : null}
      {(item.rules ?? []).map((rule) => <label key={rule.key}>Review guidance · {rule.key}<input value={rule.message} maxLength={500} onChange={(event) => update((draft) => { componentAt(draft, item.key).rules!.find((entry) => entry.key === rule.key)!.message = event.target.value; })} /></label>)}
    </article>)}</div>
    {selectedPhase === "design" ? workType.designControls ? <fieldset className="d5o-publication-fields"><legend>Design release controls · {workType.workTypeLabel}</legend>
      <p>Engineering and Safety are non-waivable. Changes take effect only through publication and apply to newly pinned work; existing releases retain their exact policy version.</p>
      <div><strong>Required discipline reviews</strong>{designReviewDisciplines.map((role) => <label key={role}><input type="checkbox" checked={workType.designControls!.requiredReviews.includes(role)} disabled={role === "Engineering" || role === "Safety"} onChange={(event) => update((draft) => { const controls = draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.designControls!; controls.requiredReviews = event.target.checked ? [...controls.requiredReviews, role] : controls.requiredReviews.filter((item) => item !== role); })} />{role}</label>)}</div>
      {([ ["requireCustomerTechnicalApproval", "External customer technical approval"], ["requireCrewDemand", "Dated skill and crew demand"], ["requireMaterialAvailability", "Physical material availability at release"], ["requirePermit", "Permit disposition"], ["requireAccess", "Confirmed access"], ["requireMop", "Method of procedure"], ["requireRollback", "Rollback or recovery method"] ] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={workType.designControls![key]} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.designControls![key] = event.target.checked; })} />{label}</label>)}
      <label><input type="checkbox" checked={workType.designControls.allowPartialRelease} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.designControls!.allowPartialRelease = event.target.checked; })} />Allow independently ready packages to be released separately</label>
      <label>Review lead time (calendar days)<input type="number" min="0" max="90" value={workType.designControls.reviewLeadDays} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.designControls!.reviewLeadDays = Number(event.target.value); })} /></label>
      <label>Procurement buffer (calendar days)<input type="number" min="0" max="90" value={workType.designControls.procurementBufferDays} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.designControls!.procurementBufferDays = Number(event.target.value); })} /></label>
    </fieldset> : <p className="d5o-phase-editor-preview-note">This older contract has no editable Design control policy. Apply the stage-aligned contract to the configuration draft first.</p> : null}
    {selectedPhase === "deploy" ? workType.deployControls ? <fieldset className="d5o-publication-fields"><legend>Deploy field controls · {workType.workTypeLabel}</legend><p>These settings govern new work pinned to this publication. Existing starts and signed records keep their original basis. Safety, independent review and client authority remain separate controls.</p>
      {([ ["requireWorkerAcknowledgment", "Worker response before start"], ["requirePhysicalMaterials", "Physical material availability"], ["requirePermit", "Permit disposition"], ["requireAccess", "Confirmed access"], ["requireReviewedEvidence", "Reviewed evidence before quality approval"], ["allowPartialAcceptance", "Allow scoped partial acceptance"] ] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={workType.deployControls![key]} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.deployControls![key] = event.target.checked; })} />{label}</label>)}
      <label>Maximum recorded hours per person and shift<input type="number" min="1" max="24" value={workType.deployControls.maxActualHoursPerShift} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.deployControls!.maxActualHoursPerShift = Number(event.target.value); })} /></label>
    </fieldset> : <button type="button" onClick={() => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.deployControls = defaultDeployControlPolicy(workType.workTypeKey); })}>Add Deploy controls to this draft</button> : null}
    {selectedPhase === "operate" ? workType.operateControls ? <fieldset className="d5o-publication-fields"><legend>Operate support controls · {workType.workTypeLabel}</legend><p>Published changes apply to newly pinned work. Support activation remains separate from Finance closeout and lifecycle sales.</p>
      {([ ["allowLegacyOnboarding", "Permit documented legacy onboarding"], ["allowPartialHandoff", "Permit scoped partial handoff"], ["requireDocumentationReview", "Review received documentation"], ["requireCustomerContact", "Require customer contact"], ["requireExplicitCoverageDisposition", "Require warranty and service dispositions"], ["allowNoCoverage", "Permit explicit no-coverage disposition"] ] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={workType.operateControls![key]} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.operateControls![key] = event.target.checked; })} />{label}</label>)}
      <label>Default response hours<input type="number" min="1" max="720" value={workType.operateControls.defaultResponseHours ?? ""} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.operateControls!.defaultResponseHours = event.target.value ? Number(event.target.value) : null; })} /></label>
      <label>Response calendar<select value={workType.operateControls.responseCalendar} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.operateControls!.responseCalendar = event.target.value as "Business hours" | "Continuous"; })}><option>Business hours</option><option>Continuous</option></select></label>
      <label>Time zone<input value={workType.operateControls.timezone} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.operateControls!.timezone = event.target.value; })} /></label>
      <label>Business day starts (local hour, 0–23)<input type="number" min="0" max="23" value={workType.operateControls.businessStartHour ?? 9} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.operateControls!.businessStartHour = Number(event.target.value); })} /></label>
      <label>Business day ends (local hour, 1–24)<input type="number" min="1" max="24" value={workType.operateControls.businessEndHour ?? 17} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.operateControls!.businessEndHour = Number(event.target.value); })} /></label>
      <label>Holidays, YYYY-MM-DD (comma separated)<input value={workType.operateControls.holidayDates.join(", ")} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.operateControls!.holidayDates = event.target.value.split(",").map((value) => value.trim()).filter(Boolean); })} /></label>
      <label>Permitted SLA pause reasons (comma separated)<input value={(workType.operateControls.slaPauseReasons ?? []).join(", ")} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.operateControls!.slaPauseReasons = event.target.value.split(",").map((value) => value.trim()).filter(Boolean); })} /></label>
      <label>Maximum maintenance recurrence days<input type="number" min="1" max="3650" value={workType.operateControls.maxMaintenanceFrequencyDays} onChange={(event) => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.operateControls!.maxMaintenanceFrequencyDays = Number(event.target.value); })} /></label>
    </fieldset> : <button type="button" onClick={() => update((draft) => { draft.workTypes.find((item) => item.workTypeKey === workType.workTypeKey)!.operateControls = defaultOperateControlPolicy(workType.workTypeKey); })}>Add Operate controls to this draft</button> : null}
  </section>;
}
