export type WorkspaceKey = "rybex" | "rotork";
export type DefinitionSource = { revision: number; configurationVersionId: string; workTypeKey: string; capturedAt: string };
import type { PricingEvaluation, PricingInput, PricingPolicy } from "./develop-pricing";
import type { DesignState } from "./design-model";
import type { DeployState } from "./deploy-model";
import type { OperateState } from "./operate-model";
export type DevelopOption = { id: string; revision: number; name: string; approach: string; requirementIds: string[]; unmetRequirements: string; deliveryModel: "Self-perform" | "Subcontract" | "Partner" | "Mixed"; materials: string; resourceBasis: string; scheduleBasis: string; safetyQuality: string; risks: string; evidence: string; owner: string; status: "Draft" | "Viable" | "Rejected"; rejectionReason?: string };
export type DevelopPlan = { revision: number; options: DevelopOption[]; selectedOptionId?: string; selectionRationale?: string; laborStrategy: string; procurementStrategy: string; scheduleStrategy: string; safetyStrategy: string; qualityStrategy: string; riskMitigation: string; targetDate: string; designOwner: string; review?: { revision: number; status: "Submitted" | "Approved" | "Returned"; dueDate: string; submittedAt: string; submittedByActorId: string; submittedByMembershipId: string; approverRole: "admin" | "operations_leader"; policyId: string; policyVersion: number; decidedAt?: string; decidedByActorId?: string; decidedByMembershipId?: string; note?: string }; history: Array<{ at: string; event: string; note: string }>; revisionHistory?: Array<{ revision: number; at: string; event: string; snapshot: Record<string, unknown> }> };
export type ProposalStatus = "Not started" | "Draft" | "Internal review" | "Changes requested" | "Approved" | "Submitted";
export type ProposalPackage = { revision: number; estimateRevision: number; scope: string; assumptions: string; exclusions: string; commercialTerms: string; sellPrice: number; preparedAt: string; definitionSource?: DefinitionSource; changeReason?: string; pricingBasis?: { policyId: string; policyVersion: number; solutionRevision: number; currency: string; includedCostMinor: number; priceMinor: number } };
export type ProposalReview = { revision: number; submittedAt: string; submittedBy: string; submittedByActorId?: string; submittedByMembershipId?: string; dueDate: string; authorityProfileId?: string; authorityRole?: string; grossMarginPercent?: number; priceChangePercent?: number; scopeChanged?: boolean; termsChanged?: boolean; decidedAt?: string; decisionNote?: string; decidedBy?: string; actorId?: string; membershipId?: string };
export type ProposalResponse = { revision: number; status: "Clarification requested" | "Commercial negotiation" | "Decision deferred" | "Awarded" | "Not awarded"; receivedAt: string; details: string; nextAction?: string; followUpDue?: string; recordedByActorId?: string; recordedByMembershipId?: string };
export type ProposalSubmission = { revision: number; estimateRevision: number; recordedAt: string; recipient: string; method: string; responseDueDate: string; packageSnapshot?: ProposalPackage; recordedByActorId?: string; recordedByMembershipId?: string };
export type DesignHandoffBrief = { offerRevision: number; estimateRevision: number; definitionRevision: number; configurationVersionId: string; customerOutcome: string; acceptance: string; offerScope: string; excludedScope: string; deliveryApproach: string; dependencies: string; risks: string; commercialTerms: string; awardBasis: string; develop?: { solutionRevision: number; selectedOption: string; selectedOptionSnapshot: DevelopOption; selectionRationale: string; policyId: string; policyVersion: number; currency: string; laborStrategy: string; procurementStrategy: string; scheduleStrategy: string; safetyStrategy: string; qualityStrategy: string; riskMitigation: string; estimateSnapshot: { input: PricingInput; evaluation: PricingEvaluation; policySnapshot: PricingPolicy }; offerSnapshot: ProposalPackage }; };
export type DesignHandoff = { revision: number; status: "submitted" | "returned" | "accepted"; brief: DesignHandoffBrief; responseDueDate: string; submittedAt: string; submittedBy: string; submittedByActorId: string; submittedByMembershipId: string; decidedAt?: string; decidedBy?: string; decidedByActorId?: string; decidedByMembershipId?: string; decisionNote?: string };
export type DesignHandoffEvent = { revision: number; state: DesignHandoff["status"]; at: string; actorId: string; membershipId: string; note: string; brief?: DesignHandoffBrief };

export type DiscoveryRecord = {
  crm?: DiscoverCRM;
  pursuitControl?: {
    revision: number;
    status: "draft" | "submitted" | "returned" | "qualified" | "held" | "declined";
    requester: string; intendedOutcome: string; roughValue: string; currency: string; requiredDate: string; knownRisk: string;
    submission?: { revision: number; at: string; actor: string };
    decision?: { revision: number; outcome: "qualified" | "held" | "declined" | "returned"; reason: string; at: string; actor: string; assessmentRevision?: number; recommendation?: string; policyVersion?: string };
    spend?: { status: "not_requested" | "requested" | "authorized" | "returned"; cap: number; purpose: string; reason?: string; actor?: string; at?: string };
    handoff?: { status: "not_started" | "submitted" | "returned" | "accepted"; receiver: string; brief: string; reason?: string; revision: number; actor?: string; at?: string };
    history: Array<{ revision: number; action: string; actor: string; at: string; note: string }>;
  };
  source: string;
  need: string;
  procurement: string;
  phase: "Qualification" | "Estimate" | "Pricing review" | "Proposal" | "Submitted" | "Validation" | "Clarification" | "Outcome";
  fit: "Unassessed" | "Qualified" | "Conditional" | "Disqualified";
  closeDate: string;
  estimate: { revision: number; labor: number; materials: number; subcontract: number; travel: number; contingency: number; targetMargin: number; sellPrice: number; status: "Not started" | "Draft" | "Pricing review" | "Approved" | "Changes requested"; assumption: string; definitionSource?: DefinitionSource; detailed?: { input: PricingInput; evaluation: PricingEvaluation; policySnapshot: PricingPolicy; savedAt: string }; revisionHistory?: Array<{ revision: number; status: string; sellPrice: number; assumption: string; detailed?: { input: PricingInput; evaluation: PricingEvaluation; policySnapshot: PricingPolicy; savedAt: string }; savedAt: string }>; review?: { revision: number; submittedAt: string; submittedBy: string; submittedByActorId?: string; submittedByMembershipId?: string; dueDate?: string; exception?: { revision: number; policyId: string; policyVersion: number; actorId: string; membershipId: string; role: string; at: string; reason: string; marginPercent: number }; decidedAt?: string; decisionNote?: string; decidedBy?: string; actorId?: string; membershipId?: string }; pricingHistory?: Array<{ revision: number; state: "Submitted" | "Approved" | "Changes requested"; at: string; note: string; cost: number; sellPrice: number; targetMargin: number }> };
  proposal: { status: ProposalStatus; dueDate: string; method: string; recipient: string; response: string; package?: ProposalPackage; packageHistory?: ProposalPackage[]; review?: ProposalReview; submission?: ProposalSubmission; submissionHistory?: ProposalSubmission[]; responseEvents?: ProposalResponse[]; history?: Array<{ revision: number; state: string; at: string; note: string }> };
  outcome?: "Won" | "Lost" | "No bid";
  outcomeNote?: string;
  designHandoff?: DesignHandoff;
  designHandoffHistory?: DesignHandoffEvent[];
};

export type DiscoverContact = { id: string; name: string; organization: string; role: "Sponsor" | "Decision-maker" | "Technical reviewer" | "Procurement" | "End user" | "Champion" | "Partner"; influence: "High" | "Medium" | "Low"; relationship: "Unknown" | "Introduced" | "Engaged" | "Supportive" | "Opposed"; note: string };
export type DiscoverActivity = { id: string; at: string; author: string; kind: "Meeting" | "Call" | "Correspondence" | "Site visit" | "Document review" | "Finding"; contacts: string[]; summary: string; resultingAction?: string; taskId?: string };
export type DiscoverTask = { id: string; title: string; owner: string; due: string; status: "Open" | "Done"; createdAt: string; completedAt?: string };
export type DiscoverAssessment = { revision: number; at: string; policyVersion: string; basis: string; recommendation: "Pursue" | "Pursue with conditions" | "Hold for information" | "Decline"; score: number | null; coverage: number; evidenceConfidence?: "No references" | "References recorded; verification unknown"; reasons: string[]; concerns: string[]; conditions: string[]; contributions: Array<{ label: string; score: number; weight: number }>; };
export type DiscoverCRM = {
  accountRef?: string; siteRef?: string; externalCrmRef?: string; customerResolved: boolean; siteResolved: boolean;
  contacts: DiscoverContact[]; activities: DiscoverActivity[]; tasks: DiscoverTask[];
  buyingProcess: string; funding: "Unknown" | "Unconfirmed" | "Confirmed"; competition: string; access: string;
  desiredOutcome?: string; businessImpact?: string; urgency?: "Unknown" | "Low" | "Normal" | "High" | "Critical"; preliminaryScope?: string; geography?: string; customerRelationship?: string;
  commercialStatus?: "Unknown" | "Early interest" | "Budgeting" | "Procurement" | "Offer requested" | "Offer submitted" | "Negotiating" | "Awarded" | "Lost";
  strategicFit: number | null; needCredibility: number | null; commercialAttractiveness: number | null; deliveryFeasibility: number | null; risk: number | null;
  disqualifier: "None" | "Legal restriction" | "Unsafe delivery" | "Outside service scope";
  forecast: { value: number | null; currency: string; basis: string; probability: number | null; awardDate: string; category: "Unspecified" | "Pipeline" | "Best case" | "Commit" | "Excluded"; rationale: string; reviewedAt?: string };
  assessmentHistory: DiscoverAssessment[];
  forecastSnapshots?: Array<{ at: string; period: string; currency: string; workRevision: number; value: number | null; probability: number | null; weighted: number | null; category?: string; awardDate?: string; workId?: string }>;
};

export type DefinitionRecord = {
  revision: number;
  sourceEstimateRevision?: number;
  sourceProposalRevision?: number;
  configurationVersion?: string;
  configurationWorkTypeKey?: string;
  registers?: Record<string, Array<Record<string, string>>>;
  status: "Draft" | "In review" | "Changes requested" | "Approved";
  outcome: string;
  acceptance: string;
  includedScope: string;
  excludedScope: string;
  deliveryApproach: string;
  milestones: string;
  dependencies: string;
  estimateBasis: string;
  commercialTerms: string;
  risks: string;
  owner: string;
  scopeControl?: {
    requirements: Array<{ id: string; need: string; source: string; owner: string; state: "Open" | "Confirmed" }>;
    interfaces: Array<{ id: string; kind: "Physical" | "Technical" | "Organizational" | "Commercial"; boundary: string; owner: string; counterparty: string; agreement: string }>;
    assumptions: Array<{ id: string; statement: string; owner: string; source: string; state: "Open" | "Accepted" | "Resolved" }>;
    customerAgreement?: { representative: string; agreedAt: string; basis: string };
    rom?: { low: string; high: string; currency: string; assumptions: string };
  };
  project?: { customerContact: string; customerContactId?: string; siteArea: string; affectedSystems: string; accessConstraints: string; requiredDate: string };
  findings?: Array<{ id: string; kind: "Survey" | "Customer input" | "Technical review" | "Document review"; status: "Provisional" | "Confirmed"; detail: string; source: string; author: string; at: string }>;
  clarifications?: Array<{ id: string; question: string; owner: string; due: string; answer: string; source: string; status: "Open" | "Answered"; openedAt: string; answeredAt?: string }>;
  developHandoff?: { revision: number; status: "submitted" | "returned" | "accepted"; receiver: string; note: string; submittedAt: string; respondedAt?: string; actor: string; submittedByActorId?: string; submittedByMembershipId?: string; receivedByActorId?: string; receivedByMembershipId?: string };
  decisions?: Array<{ commandId: string; fingerprint: string; action: string; definitionRevision: number; reviewRole?: "commercial" | "delivery"; actorId: string; membershipId: string; policyVersion: string; at: string; reason: string }>;
  approvedBaselines?: Array<{ revision: number; approvedAt: string; configurationVersion: string; outcome: string; excludedScope: string; deliveryApproach: string; registers: Record<string, Array<Record<string, string>>>; project?: DefinitionRecord["project"]; findings: NonNullable<DefinitionRecord["findings"]>; clarifications: NonNullable<DefinitionRecord["clarifications"]>; scopeControl?: DefinitionRecord["scopeControl"] }>;
  reviews?: { commercial: "Pending" | "Approved" | "Changes requested"; delivery: "Pending" | "Approved" | "Changes requested"; revision: number };
  history: Array<{ at: string; revision: number; event: string; note: string }>;
};

export type WorkRecord = {
  id: string; workspace: WorkspaceKey; title: string; type: string; customer: string; site: string; stage: string; owner: string;
  phaseConfigurationVersionId?: string;
  nextAction: string; nextActionDue?: string | null; nextActionImpact?: "Critical" | "High" | "Standard" | null;
  progress: number; value: string; status: "attention" | "moving" | "complete"; proof: string[]; blockers: string[]; history: string[];
  commercial?: { condition: string; amount: string; confidence: string };
  discovery?: DiscoveryRecord;
  definition?: DefinitionRecord;
  develop?: DevelopPlan;
  design?: DesignState;
  deploy?: DeployState;
  operate?: OperateState;
  serviceSource?: { parentWorkId: string; assetIds: string[]; requestId?: string; maintenancePlanId?: string; pricing?: { estimateRevision: number; policyId: string; policyVersion: number; currency: string; amountMinor: number; customerAuthorizationSource: string } };
  packages?: Array<{ id: string; name: string; owner: string; installed: number; tested: number; accepted: number; status: "planned" | "in progress" | "ready" | "accepted"; acceptanceBasis?: string }>;
  phaseRegisters?: Record<string, Array<Record<string, string>>>;
};
