import type { OperatingWorkflowType, WorkflowTypeConfig } from "./types";

const toneBySeverity: WorkflowTypeConfig["toneBySeverity"] = {
  critical: "critical",
  high: "warning",
  watch: "info",
  info: "neutral",
  resolved: "success"
};

const statusLanguage: WorkflowTypeConfig["statusLanguage"] = {
  needs_decision: "Decision needed",
  needs_action: "Action required",
  blocked: "Blocked",
  overdue: "Overdue",
  in_progress: "In progress",
  ready_for_review: "Ready for review",
  resolved: "Resolved"
};

export const workflowTypeConfig: Record<OperatingWorkflowType, WorkflowTypeConfig> = {
  pursuit_control: {
    label: "Pursuit Control",
    shortLabel: "D1 Pursuit",
    purpose: "Protect estimating capacity and margin before Rybex commits to bid.",
    primaryQuestion: "Should Rybex pursue this work?",
    typicalSignals: ["Bid due soon", "High-risk pursuit", "Go/no-go not approved"],
    typicalDecisions: ["Approve to bid", "Hold for clarification", "Decline/no-bid"],
    typicalActions: ["Complete go/no-go review", "Resolve pursuit risk", "Assign reviewer decision"],
    typicalEvidence: ["Score detail", "Reviewer notes", "Bid documents", "Risk mitigations"],
    targetModule: "Pipeline",
    targetHref: "/pipeline",
    d5oPhase: "discover",
    statusLanguage,
    toneBySeverity
  },
  contract_baseline: {
    label: "Contract Baseline",
    shortLabel: "D2 Define",
    purpose: "Control scope, contract terms, budget, schedule, and handoff before mobilization planning.",
    primaryQuestion: "Is the sold work defined enough to move toward D3?",
    typicalSignals: ["Missing contract summary", "Scope matrix gap", "Notice terms unclear"],
    typicalDecisions: ["Release to D3 planning", "Hold for contract review", "Hold for scope/budget/schedule baseline"],
    typicalActions: ["Complete contract baseline", "Resolve exclusions and assumptions", "Approve D2 gate"],
    typicalEvidence: ["Contract summary", "Scope matrix", "Budget baseline", "Schedule baseline", "Notice requirements"],
    targetModule: "Projects",
    targetHref: "/projects",
    d5oPhase: "define",
    statusLanguage,
    toneBySeverity
  },
  mobilization_readiness: {
    label: "Mobilization Readiness",
    shortLabel: "D3 Prepare",
    purpose: "Confirm the project is field-ready before work starts.",
    primaryQuestion: "Can the crew safely and productively mobilize?",
    typicalSignals: ["Missing JHA", "Utility locates not confirmed", "Materials not delivered", "Site access not confirmed"],
    typicalDecisions: ["Approve field start", "Hold for safety", "Hold for access/permits", "Hold for materials"],
    typicalActions: ["Confirm locates/access/materials", "Complete safety package", "Release work packages"],
    typicalEvidence: ["JHA", "Utility locate confirmation", "Crew/equipment/material readiness", "Site access confirmation"],
    targetModule: "Mobilization",
    targetHref: "/mobilization",
    d5oPhase: "prepare",
    statusLanguage,
    toneBySeverity
  },
  field_execution: {
    label: "Field Execution",
    shortLabel: "D4 Deliver",
    purpose: "Capture daily proof, production, blockers, delays, and escalation prompts while work is performed.",
    primaryQuestion: "What happened in the field and what must be escalated?",
    typicalSignals: ["Missing daily report", "Changed condition", "Production behind", "Supervisor signoff pending"],
    typicalDecisions: ["Continue work", "Create RFI", "Create change event", "Hold work"],
    typicalActions: ["Submit daily report", "Document delay", "Flag RFI/change prompt", "Complete signoff"],
    typicalEvidence: ["Daily report", "Installed quantities", "Photos", "Supervisor signoff", "Field notes"],
    targetModule: "Field Execution",
    targetHref: "/field-execution",
    d5oPhase: "deliver",
    statusLanguage,
    toneBySeverity
  },
  information_control: {
    label: "Information Control",
    shortLabel: "RFI/Submittal",
    purpose: "Control clarifications and approvals that affect field work, schedule, and entitlement.",
    primaryQuestion: "What clarification or approval is blocking work?",
    typicalSignals: ["Overdue RFI", "Submittal blocking work", "Schedule-critical response due"],
    typicalDecisions: ["Escalate response", "Revise/resubmit", "Link to change event"],
    typicalActions: ["Submit RFI", "Update submittal", "Escalate overdue response"],
    typicalEvidence: ["Question", "Drawing/spec reference", "Submittal package", "Response record"],
    targetModule: "RFIs & Submittals",
    targetHref: "/rfis-submittals",
    d5oPhase: "deliver",
    statusLanguage,
    toneBySeverity
  },
  change_recovery: {
    label: "Change Recovery",
    shortLabel: "Changes",
    purpose: "Turn changed conditions, extra work, and GC direction into controlled commercial recovery.",
    primaryQuestion: "What work, delay, or direction needs commercial recovery?",
    typicalSignals: ["Notice deadline", "Missing backup", "Pricing required", "Approved change not billed"],
    typicalDecisions: ["Submit notice", "Request pricing", "Submit pricing", "Mark disputed"],
    typicalActions: ["Create change event", "Attach backup", "Price impact", "Link billing recovery"],
    typicalEvidence: ["Daily report", "Photos", "RFI response", "Directive", "T&M ticket"],
    targetModule: "Change Control",
    targetHref: "/changes",
    d5oPhase: "deliver",
    statusLanguage,
    toneBySeverity
  },
  billing_cash_control: {
    label: "Billing / Cash Control",
    shortLabel: "Billing",
    purpose: "Convert completed work, approved changes, and backup into clean pay application readiness.",
    primaryQuestion: "What can we bill, what is blocked, and what cash is at risk?",
    typicalSignals: ["Approved change not billed", "Pay app aging", "Missing backup", "Lien waiver missing"],
    typicalDecisions: ["Include in pay app", "Hold for backup", "Escalate aging payment"],
    typicalActions: ["Add approved change", "Attach backup", "Resolve waiver", "Follow up payment"],
    typicalEvidence: ["Approved change", "Daily reports", "Quantity records", "Lien waiver", "Pay application support"],
    targetModule: "Billing",
    targetHref: "/billing",
    d5oPhase: "deliver",
    statusLanguage,
    toneBySeverity
  },
  safety_control: {
    label: "Safety Control",
    shortLabel: "Safety",
    purpose: "Control safety readiness, observations, incidents, and corrective actions.",
    primaryQuestion: "Are safety requirements complete and corrective actions controlled?",
    typicalSignals: ["Missing JHA", "Open observation", "Incident follow-up", "Overdue corrective action"],
    typicalDecisions: ["Hold work", "Verify corrective action", "Escalate incident follow-up"],
    typicalActions: ["Complete JHA", "Assign corrective action", "Verify closure", "Attach safety evidence"],
    typicalEvidence: ["JHA", "Toolbox talk", "Observation photo", "Incident report", "Verification record"],
    targetModule: "Safety",
    targetHref: "/safety",
    d5oPhase: "deliver",
    statusLanguage,
    toneBySeverity
  },
  quality_control: {
    label: "Quality Control",
    shortLabel: "Quality",
    purpose: "Control inspections, deficiencies, tests, punch items, and acceptance evidence.",
    primaryQuestion: "Has the work been inspected, tested, corrected, and proven?",
    typicalSignals: ["Failed inspection", "Open deficiency", "Missing test", "Punch item blocking acceptance"],
    typicalDecisions: ["Correct and reinspect", "Hold closeout", "Escalate quality action"],
    typicalActions: ["Assign correction", "Upload test result", "Verify deficiency", "Close punch item"],
    typicalEvidence: ["Inspection record", "Test result", "Photo evidence", "Correction verification", "Punch closure"],
    targetModule: "Quality",
    targetHref: "/quality",
    d5oPhase: "deliver",
    statusLanguage,
    toneBySeverity
  },
  closeout_acceptance: {
    label: "Closeout / Acceptance",
    shortLabel: "D5 Close",
    purpose: "Prove completion, secure acceptance, support final billing, and release retainage.",
    primaryQuestion: "Can Rybex prove completion, secure acceptance, and recover final payment?",
    typicalSignals: ["Missing test record", "Punch blocker", "Final billing blocker", "Retainage release blocker"],
    typicalDecisions: ["Submit for acceptance", "Hold for evidence", "Hold for final billing", "Archive package"],
    typicalActions: ["Resolve blocker", "Attach evidence", "Submit package", "Release retainage request"],
    typicalEvidence: ["As-builts", "Test records", "Punch closure", "Final pay app", "Lien waiver", "GC acceptance"],
    targetModule: "Closeout",
    targetHref: "/closeout",
    d5oPhase: "close",
    statusLanguage,
    toneBySeverity
  },
  optimize_learning: {
    label: "Optimize / Learning",
    shortLabel: "Optimize",
    purpose: "Turn completed work into better estimating, planning, partner selection, and execution discipline.",
    primaryQuestion: "What should Rybex change before the next project?",
    typicalSignals: ["Production variance", "Open lesson", "Overdue improvement action", "GC/vendor warning"],
    typicalDecisions: ["Update estimating assumption", "Assign process action", "Adjust pursuit posture"],
    typicalActions: ["Publish lesson", "Update production rate", "Assign improvement", "Update risk library"],
    typicalEvidence: ["Lessons learned review", "Production records", "Scorecard", "GC/vendor performance profile"],
    targetModule: "Optimize",
    targetHref: "/reports",
    d5oPhase: "optimize",
    statusLanguage,
    toneBySeverity
  },
  system_readiness: {
    label: "System Readiness",
    shortLabel: "Admin",
    purpose: "Keep the demo/platform operating safely, transparently, and with known implementation boundaries.",
    primaryQuestion: "Is the platform operating safely and transparently?",
    typicalSignals: ["Demo mode boundary", "Persistence disabled", "Visual QA review", "Route health"],
    typicalDecisions: ["Ready for demo", "Hold for review", "Approve next hardening phase"],
    typicalActions: ["Run verification", "Review readiness docs", "Preserve seed fallback"],
    typicalEvidence: ["Smoke routes", "Visual QA report", "Persistence docs", "Implementation status"],
    targetModule: "Admin",
    targetHref: "/admin",
    d5oPhase: "optimize",
    statusLanguage,
    toneBySeverity
  }
};

export const workflowTypeOrder: OperatingWorkflowType[] = [
  "pursuit_control",
  "contract_baseline",
  "mobilization_readiness",
  "field_execution",
  "information_control",
  "change_recovery",
  "billing_cash_control",
  "safety_control",
  "quality_control",
  "closeout_acceptance",
  "optimize_learning",
  "system_readiness"
];
