import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync,existsSync,readdirSync} from 'node:fs';
import {resolve,basename} from 'node:path';
import {spawnSync} from 'node:child_process';
import {boundary,hash,sql,evidence} from './implementation-context.mjs';
const approved=JSON.parse(readFileSync(resolve(evidence,'replay-2026-09-28T22-33-41-006Z/GATE-MANIFEST.json')));
export function validateSelection(m,end){
 assert.equal(m.project,approved.project,'wrong_project');assert.equal(m.api,approved.api,'wrong_api');assert.equal(resolve(m.root),process.cwd(),'wrong_root');assert.equal(m.ownershipSha256,approved.ownershipSha256,'ownership_manifest');assert([33,34,35].includes(end),'invalid_prefix');assert([34,35].includes(m.replay.length),'missing_source');assert(end<=m.replay.length,'missing_source');
 if(m.replay.length===35){const seal=JSON.parse(readFileSync(resolve(evidence,'replay-guard-correction-20260929-01/AUTHORIZATION-SEAL.json')));assert.equal(seal.migration.sha256,'9dd4dc9ece353557378e7dfae733b39283832b3fdf2008c03b99d436069d0a90','amendment_seal');assert.deepEqual(m.replay[34],seal.migration,'unapproved_extra_source');assert.equal(hash(readFileSync(m.replay[34].path)),seal.migration.sha256,'extra_source_bytes');}else assert(end!==35,'missing_amendment');
 const versions=new Set();for(let i=0;i<34;i++){const x=m.replay[i],a=approved.replay[i];assert.equal(x.order,i+1,'order');assert.equal(x.source,a.source,'source_variant');assert.equal(x.sha256,a.sha256,'source_hash');assert.equal(resolve(x.path),resolve(a.path),'source_path');assert.equal(x.staged_name,a.staged_name,'staged_name');const name=x.staged_name??basename(x.path);assert(/^\d+_[\w-]+\.sql$/.test(name),'filename');const version=name.split('_')[0];assert(!versions.has(version),'duplicate_version');versions.add(version);assert.equal(hash(readFileSync(x.path)),x.sha256,'source_bytes');}
 return m.replay.slice(0,end).map(x=>({...x,filename:x.staged_name??basename(x.path),version:(x.staged_name??basename(x.path)).split('_')[0],name:(x.staged_name??basename(x.path)).replace(/^\d+_/,'').replace(/\.sql$/,'')}));
}
export function ledger(){const exists=sql("begin read only;select to_regclass('supabase_migrations.schema_migrations') is not null;commit;");if(exists==='f')return [];return JSON.parse(sql("begin read only;select coalesce(jsonb_agg(jsonb_build_object('version',version,'name',name,'statementCount',cardinality(statements),'statementsSha256',encode(extensions.digest(convert_to(statements::text,'UTF8'),'sha256'),'hex')) order by version),'[]') from supabase_migrations.schema_migrations;commit;"));}
export function runMigrations(m,end,label){
 const entries=validateSelection(m,end);boundary();assert(resolve(m.private).startsWith(resolve('.rybexos-local/m1-s1')+'\\'),'private_boundary');assert(resolve(m.evidence).startsWith(evidence+'\\'),'evidence_boundary');assert(/^[a-z0-9-]+$/.test(label),'label');
 const out=resolve(m.evidence,label+'-runner.json');assert(!existsSync(out),'no_overwrite');const before=ledger();assert(before.every(x=>entries.some(y=>y.version===x.version&&y.name===x.name)),'unexpected_recorded_migration');
 const hasM1=sql("begin read only;select to_regclass('public.d5o_work_records') is not null;commit;")==='t';assert(!hasM1||before.some(x=>x.version==='20260928214119'),'unrecorded_m1_objects');
 const stage=resolve(m.private,'cli-'+label),dir=resolve(stage,'supabase','migrations');mkdirSync(dir,{recursive:true});const config=readFileSync('.rybexos-local/m1-s1/brc-recovery/supabase/config.toml','utf8');assert(config.includes('project_id = "'+m.project+'"')&&config.includes('port = 61422'),'config_target');assert(!/env\(|supabase\.co|project_ref/.test(config),'config_external_reference');writeFileSync(resolve(stage,'supabase/config.toml'),config);
 for(const x of entries)writeFileSync(resolve(dir,x.filename),readFileSync(x.path));assert.equal(readdirSync(dir).length,end);
 const keys=new Set(['PATH','SYSTEMROOT','WINDIR','COMSPEC','PATHEXT','TEMP','TMP','APPDATA','LOCALAPPDATA','USERPROFILE','PROGRAMFILES']);const env=Object.fromEntries(Object.entries(process.env).filter(([k])=>keys.has(k.toUpperCase())));Object.assign(env,{SUPABASE_HOME:resolve('.rybexos-local/m1-s1/cli-home'),SUPABASE_TELEMETRY_DISABLED:'1',DO_NOT_TRACK:'1',CI:'1'});
 const cli=resolve('.rybexos-local/m1-s1/toolchain/supabase-go.exe');const version=spawnSync(cli,['--version'],{env,encoding:'utf8',windowsHide:true});assert.equal(version.status,0);assert.equal(version.stdout.trim(),'2.109.1','pinned_cli');
 const seal={project:m.project,db:boundary(),cliSha256:hash(readFileSync(cli)),cliVersion:version.stdout.trim(),stage,configSha256:hash(Buffer.from(config)),entries:entries.map(x=>({version:x.version,name:x.name,sha256:x.sha256})),before};writeFileSync(resolve(m.evidence,label+'-seal.json'),JSON.stringify(seal,null,2));
 const result=spawnSync(cli,['migration','up','--local','--workdir',stage,'--yes'],{env,encoding:'utf8',windowsHide:true,maxBuffer:12*1024*1024});
 const scrub=s=>s.replace(/postgres(?:ql)?:\/\/[^\s]+/g,'[REDACTED_CONNECTION]');writeFileSync(out,JSON.stringify({exit:result.status,stdout:scrub(result.stdout),stderr:scrub(result.stderr)},null,2));assert.equal(result.status,0,'migration_execution_failed');boundary();const after=ledger();assert.deepEqual(after.map(x=>[x.version,x.name]),entries.map(x=>[x.version,x.name]),'ledger_exact_selection');assert(after.every(x=>x.statementCount>0&&x.statementsSha256),'missing_statement_provenance');for(const x of before)assert.deepEqual(after.find(y=>y.version===x.version),x,'existing_ledger_changed');writeFileSync(resolve(m.evidence,label+'-ledger.json'),JSON.stringify(after,null,2));return {before,after,applied:end-before.length};
}
