import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {createServer} from 'node:net';
import {chromium} from '@playwright/test';
import {context,evidence,save,sql,q,loadWork,command} from './implementation-context.mjs';
import {prepare,decide} from './proof-fixtures.mjs';
const c=await context(),plan=JSON.parse(readFileSync(process.argv[2])),f=plan.scenarios[0],tag=new Date().toISOString().replaceAll(/[:.]/g,'-'),results=[],errors=[];
const shots=resolve(evidence,'browser-'+tag);mkdirSync(shots);const nextEnv=readFileSync('next-env.d.ts');let server,browser;let logs='';
const env={...c.env,M1_PROOF_ENABLED:'1',NEXT_TELEMETRY_DISABLED:'1',NODE_ENV:'production'};const base='http://127.0.0.1:61430';
async function login(role,fixture=f){const ctx=await browser.newContext({viewport:{width:1440,height:1000}});await ctx.route('**/*',route=>{const u=new URL(route.request().url());return ['http://127.0.0.1:61430','http://127.0.0.1:61421'].includes(u.origin)?route.continue():route.abort();});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/auth/sign-in?next=%2Fm1-proof');await page.getByLabel('Email',{exact:true}).fill(fixture.actors[role].email);await page.getByLabel('Password',{exact:true}).fill(c.env.FOUNDATION_0A_TEST_PASSWORD);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/m1-proof',{timeout:30000});return {ctx,page};}
const url=w=>base+`/m1-proof?workspace=${f.workspace}&work=${w}`;
async function shot(page,name){await page.screenshot({path:resolve(shots,name+'.png'),fullPage:true});results.push({name,status:'PASS'});}
try{
 await new Promise((ok,no)=>{const s=createServer();s.once('error',no);s.listen(61430,'127.0.0.1',()=>s.close(ok));});
 const build=spawnSync(process.execPath,['node_modules/next/dist/bin/next','build'],{env,encoding:'utf8',windowsHide:true,maxBuffer:8*1024*1024});save('build-'+tag+'.json',{exit:build.status,stdout:build.stdout,stderr:build.stderr});assert.equal(build.status,0,'build failed');
 server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','-H','127.0.0.1','-p','61430'],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});server.stdout.on('data',b=>logs+=b);server.stderr.on('data',b=>logs+=b);
 let ready=false;for(let i=0;i<90;i++){try{const r=await fetch(base+'/m1-proof');if(r.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,500));}assert(ready,'server unavailable');
 browser=await chromium.launch({headless:true});
 const defaultReview=await browser.newContext({viewport:{width:1440,height:1000}}),defaultReviewPage=await defaultReview.newPage();await defaultReviewPage.goto(base+'/auth/sign-in');await defaultReviewPage.getByLabel('Email',{exact:true}).fill(f.actors.quality_verifier.email);await defaultReviewPage.getByLabel('Password',{exact:true}).fill(c.env.FOUNDATION_0A_TEST_PASSWORD);await defaultReviewPage.getByRole('button',{name:'Sign in',exact:true}).click();await defaultReviewPage.waitForURL('**/m1-proof');assert.equal(await defaultReviewPage.getByRole('link',{name:/D5O/i}).getAttribute('href'),'/m1-proof');assert.equal(await defaultReviewPage.getByText('M1-S1 synthetic architecture review',{exact:true}).count(),1);assert.equal(await defaultReviewPage.getByRole('link',{name:/Command Center/i}).count(),0);await defaultReview.close();results.push({name:'default-reviewer-landing-is-isolated',status:'PASS'});
 const work=await prepare(c,f),quality=await login('quality_verifier');await quality.page.goto(url(work.work));await quality.page.getByRole('heading',{name:'What needs attention'}).waitFor();assert.match(await quality.page.getByRole('region',{name:'Workspace identity'}).innerText(),/Synthetic rybex proof/i);assert.match(await quality.page.title(),/Synthetic rybex proof/);assert.equal(await quality.page.locator('form').count(),0);await quality.page.getByLabel('Choose a decision',{exact:true}).selectOption('verify-quality');assert(await quality.page.getByRole('button',{name:f.pack.rights.find(r=>r.key==='verify-quality').label,exact:true}).isEnabled());await shot(quality.page,'ready');
 const anonymous=await browser.newContext();const anonymousPage=await anonymous.newPage();await anonymousPage.goto(url(work.work));await anonymousPage.waitForURL('**/auth/sign-in?next=**');assert.match(await anonymousPage.locator('input[name="next"]').inputValue(),/m1-proof\?workspace=/);assert.match(await anonymousPage.locator('input[name="next"]').inputValue(),/work=/);await anonymous.close();results.push({name:'unauthenticated-review-redirect',status:'PASS'});
 await quality.page.locator('form').filter({has:quality.page.getByRole('button',{name:f.pack.rights.find(r=>r.key==='verify-quality').label,exact:true})}).locator('textarea').fill('Browser verified quality decision');await quality.page.getByRole('button',{name:f.pack.rights.find(r=>r.key==='verify-quality').label,exact:true}).click();await quality.page.waitForURL('**result=recorded');assert.equal((await loadWork(work.owner,f,work.work)).decisions.length,1);await shot(quality.page,'decision-recorded');
 const stale=await prepare(c,f);await quality.page.goto(url(stale.work));await quality.page.getByLabel('Choose a decision',{exact:true}).selectOption('verify-quality');await command(stale.owner,f,stale.work,'metadata',{title:'Changed after browser read'});await quality.page.locator('form').filter({has:quality.page.getByRole('button',{name:f.pack.rights.find(r=>r.key==='verify-quality').label,exact:true})}).locator('textarea').fill('Stale browser attempt');await quality.page.getByRole('button',{name:f.pack.rights.find(r=>r.key==='verify-quality').label,exact:true}).click();await quality.page.waitForURL('**result=concurrency_conflict');assert.equal((await loadWork(stale.owner,f,stale.work)).decisions.length,0);await shot(quality.page,'stale');
 const held=await prepare(c,f,{failed:true});await decide(c,f,held.work,'hold-quality');await quality.page.goto(url(held.work));await quality.page.getByText('The package is held.',{exact:false}).waitFor();await shot(quality.page,'held');
 const audit=await login('auditor');await audit.page.goto(url(work.work));await audit.page.getByText('Read-only review.',{exact:false}).waitFor();assert.equal(await audit.page.locator('form').count(),0);await shot(audit.page,'read-only');
 const old=sql(`select status from config_configuration_versions where id=${q(f.version)};`);try{sql(`update config_configuration_versions set status='draft' where id=${q(f.version)};`);await quality.page.goto(url(work.work));await quality.page.getByRole('heading',{name:'Configuration unavailable'}).waitFor();assert.equal(await quality.page.locator('form').count(),0);await shot(quality.page,'configuration-unavailable');}finally{sql(`update config_configuration_versions set status=${q(old)} where id=${q(f.version)};`);}
 const choices=await prepare(c,f);await quality.page.goto(url(choices.work));const selector=quality.page.getByLabel('Choose a decision',{exact:true});assert.equal(await selector.inputValue(),'');assert.equal(await quality.page.locator('form').count(),0);
 await selector.focus();await selector.press('Home');await selector.press('ArrowDown');await selector.press('Enter');assert.notEqual(await selector.inputValue(),'');assert.equal(await quality.page.locator('form').count(),1);
 await selector.selectOption('verify-quality');const commandId=await quality.page.locator('input[name="commandId"]').inputValue();await selector.selectOption('hold-quality');assert.equal(await quality.page.locator('form').count(),1);await selector.selectOption('verify-quality');assert.equal(await quality.page.locator('input[name="commandId"]').inputValue(),commandId);assert.equal(await quality.page.locator('input[name="rightKey"]').inputValue(),'verify-quality');assert.equal(await quality.page.locator('input[name="workspaceId"]').inputValue(),f.workspace);assert.equal(await quality.page.locator('input[name="workId"]').inputValue(),choices.work);assert.equal(await quality.page.locator('input[name="recordVersion"]').inputValue(),String((await loadWork(choices.owner,f,choices.work)).work.record_version));assert.equal(await quality.page.locator('input[name="proofRevision"]').inputValue(),'1');await shot(quality.page,'decision-choice-keyboard-and-payload');
 const acceptor=await login('owner_acceptor');await acceptor.page.goto(url(choices.work));await acceptor.page.getByLabel('Choose a decision',{exact:true}).selectOption('accept-turnover');assert(await acceptor.page.getByRole('button',{name:f.pack.rights.find(r=>r.key==='accept-turnover').label,exact:true}).isDisabled());await acceptor.page.getByText('This decision is blocked until these requirements are satisfied:').waitFor();await shot(acceptor.page,'blocked-acceptance');
 await decide(c,f,choices.work,'verify-quality');await decide(c,f,choices.work,'accept-turnover');await acceptor.page.goto(url(choices.work));assert.equal(await acceptor.page.locator('form').count(),0);await acceptor.page.getByText('This gate is complete.',{exact:false}).waitFor();await shot(acceptor.page,'completed-gate');
 const rotork=plan.scenarios[1],pilot=await prepare(c,rotork),pilotReviewer=await login('pilot_reviewer',rotork);await pilotReviewer.page.goto(base+`/m1-proof?workspace=${rotork.workspace}&work=${pilot.work}`);await pilotReviewer.page.getByRole('heading',{name:'What needs attention'}).waitFor();assert.match(await pilotReviewer.page.getByRole('region',{name:'Workspace identity'}).innerText(),/Synthetic rotork proof/i);assert.match(await pilotReviewer.page.title(),/Synthetic rotork proof/);assert(!/rybex/i.test(await pilotReviewer.page.getByRole('region',{name:'Workspace identity'}).innerText()));assert.equal(await pilotReviewer.page.getByLabel('Choose a decision',{exact:true}).inputValue(),'');await pilotReviewer.page.getByLabel('Choose a decision',{exact:true}).selectOption('review-pilot');assert(await pilotReviewer.page.getByRole('button',{name:rotork.pack.rights.find(r=>r.key==='review-pilot').label,exact:true}).isEnabled());assert.equal(await pilotReviewer.page.locator('input[name="rightKey"]').inputValue(),'review-pilot');await shot(pilotReviewer.page,'rotork-configured-review');
 assert.deepEqual(errors,[]);save('BROWSER-'+tag+'.json',{status:'PASS',results,pageErrors:errors,screenshotDirectory:shots});console.log(JSON.stringify({pass:results.length,shots}));
}catch(e){const pages=browser?.contexts().flatMap(x=>x.pages())??[];for(let i=0;i<pages.length;i++)await pages[i].screenshot({path:resolve(shots,'failure-'+i+'.png'),fullPage:true});save('BROWSER-DIAGNOSTICS-'+tag+'.json',{urls:pages.map(x=>x.url()),logs});save('BROWSER-'+tag+'.json',{status:'FAIL',error:e.message,results,pageErrors:errors});console.error(e.message);process.exitCode=1;}
finally{if(browser)await browser.close();if(server){server.kill();await new Promise(r=>server.once('exit',r));}writeFileSync('next-env.d.ts',nextEnv);}
